### ISSUE TITLE
Same shortid and open original URL error

### ISSUE THREAD

**Issue by taiqn** [Ernest2026/Url-shortener#1]
Hi, I just tested on https://s-u-r-l.herokuapp.com/ with lots of different URLs but it still show same shortid. And when I clicked on the shortened URL to open original one, error happened: https//, you missed the ":".

Hope you could fix that.

**Comment by ernestbrixx** [comment]
Thank you very much for reaching out, I'll fix the issue as soon as I can...

**Comment by ernestbrixx** [comment]
> Hi, I just tested on https://s-u-r-l.herokuapp.com/ with lots of different URLs but it still show same shortid. And when I clicked on the shortened URL to open original one, error happened: https//, you missed the ":".
> 
> Hope you could fix that.

I've fixed the bugs @taiqn
